import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    cli: "src/cli.ts",
    server: "src/server.ts",
    sdk: "src/sdk.ts",
    db: "src/db.ts",
    types: "src/types.ts",
    query: "src/query.ts",
    setup: "src/setup.ts",
    doctor: "src/doctor.ts",
    repo: "src/repo.ts",
    prune: "src/db/prune.ts",
    pricing: "src/db/pricing.ts",
    permissions: "src/mcp/permissions.ts",
    index: "src/index.ts",
    "hooks/handler": "src/hooks/handler.ts",
    "mcp/server": "src/mcp/server.ts",
    "otlp/server": "src/otlp/server.ts",
    "proxy/server": "src/proxy/server.ts",
  },
  format: ["esm"],
  target: "node22",
  platform: "node",
  splitting: true,
  clean: true,
  sourcemap: true,
  shims: true,
  dts: true,
});
