import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { z } from "zod";
import { config } from "../config.js";

const PERMISSIONS_DIR = path.join(config.dataDir, "permissions");
const APPROVALS_PATH = path.join(PERMISSIONS_DIR, "approvals.json");
const ALLOWED_PATH = path.join(PERMISSIONS_DIR, "allowed.json");
const BACKUPS_DIR = path.join(PERMISSIONS_DIR, "backups");

const DEFAULT_APPROVALS = {
  approved_categories: ["safe"],
  denied_categories: [] as string[],
  custom_overrides: {} as Record<string, string>,
  last_run: null as string | null,
};

function readJson(filePath: string): any {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf-8"));
  } catch {
    return null;
  }
}

function readText(filePath: string): string | null {
  try {
    return fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}

// Atomic write via tmp sibling + rename. POSIX rename(2) is atomic on the
// same filesystem, so readers either see the pre-rename or post-rename
// contents, never a partial write.
function writeAtomic(filePath: string, contents: string): void {
  const tmp = `${filePath}.tmp`;
  fs.writeFileSync(tmp, contents);
  fs.renameSync(tmp, filePath);
}

function writeJsonAtomic(filePath: string, content: unknown): void {
  writeAtomic(filePath, `${JSON.stringify(content, null, 2)}\n`);
}

// ─────────────────────────────────────────────────────────────────────────
// Codex target
// ─────────────────────────────────────────────────────────────────────────

interface CodexLocation {
  installed: boolean;
  rules_path: string | null;
  rules_dir: string | null;
}

// Resolve Codex location at call time — `PANOPTICON_CODEX_DIR` env overrides
// the default `~/.codex`. Re-resolved on every call so tests that mutate
// the env var per-case still work.
function locateCodex(): CodexLocation {
  const dir =
    process.env.PANOPTICON_CODEX_DIR ?? path.join(os.homedir(), ".codex");
  if (!fs.existsSync(dir)) {
    return { installed: false, rules_path: null, rules_dir: null };
  }
  const rules_dir = path.join(dir, "rules");
  return {
    installed: true,
    rules_dir,
    rules_path: path.join(rules_dir, "panopticon.rules"),
  };
}

function buildCodexRules(bashCommands: string[], now: string): string {
  const lines = [
    "# Auto-generated by panopticon — do not edit manually.",
    `# Updated: ${now}`,
    "#",
    "# Run /optimize-permissions to regenerate from observed tool usage.",
    "",
  ];
  for (const cmd of bashCommands) {
    const tokens = cmd.split(/\s+/);
    const pattern = tokens.map((t) => JSON.stringify(t)).join(", ");
    lines.push(
      `prefix_rule(pattern = [${pattern}], decision = "allow", justification = "Approved by panopticon")`,
    );
  }
  return `${lines.join("\n")}\n`;
}

// Extract the `git status` / `npx tsup` base command from a rules file line —
// used so we can diff by base command instead of by entire rendered line
// (timestamps in the header would otherwise always diff).
const RULE_PATTERN_RE = /^prefix_rule\(pattern = \[(.+?)\], decision = "allow"/;

function parseCodexRulesBaseCommands(rules: string | null): string[] {
  if (!rules) return [];
  const out: string[] = [];
  for (const line of rules.split("\n")) {
    const m = line.match(RULE_PATTERN_RE);
    if (!m) continue;
    // pattern tokens are JSON-encoded strings separated by ", ".
    const tokens: string[] = [];
    try {
      // Wrap in brackets so JSON.parse treats it as an array.
      const parsed = JSON.parse(`[${m[1]}]`) as unknown[];
      for (const t of parsed) if (typeof t === "string") tokens.push(t);
    } catch {
      continue;
    }
    out.push(tokens.join(" "));
  }
  return out;
}

export interface CodexShowState {
  installed: boolean;
  rules_path: string | null;
  rule_count: number;
}

function describeCodex(): CodexShowState {
  const loc = locateCodex();
  if (!loc.installed || !loc.rules_path) {
    return { installed: false, rules_path: null, rule_count: 0 };
  }
  const rules = readText(loc.rules_path);
  return {
    installed: true,
    rules_path: loc.rules_path,
    rule_count: parseCodexRulesBaseCommands(rules).length,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Show
// ─────────────────────────────────────────────────────────────────────────

export function permissionsShow() {
  const approvals = readJson(APPROVALS_PATH) ?? DEFAULT_APPROVALS;
  const allowed = readJson(ALLOWED_PATH) ?? {
    bash_commands: [],
    tools: [],
  };

  return {
    approvals,
    approvals_path: APPROVALS_PATH,
    allowed,
    allowed_path: ALLOWED_PATH,
    codex: describeCodex(),
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Shared input + intended state
// ─────────────────────────────────────────────────────────────────────────

export const categorySchema = z.object({
  status: z.enum(["approved", "denied", "skipped"]),
  patterns: z.array(z.string()),
  observed_commands: z.array(z.string()),
  call_count: z.number(),
});

export type CategoryEntry = z.infer<typeof categorySchema>;

export interface PermissionsInput {
  repository?: string;
  approved_categories: string[];
  denied_categories: string[];
  custom_overrides?: Record<string, string>;
  permissions: string[];
  categories: Record<string, CategoryEntry>;
}

export type PermissionsApplyParams = PermissionsInput;

const BASH_PATTERN = /^Bash\((.+?)[\s:]\*\)$/;

interface AllowedState {
  bash_commands: string[];
  tools: string[];
  updated?: string;
}

interface ApprovalsState {
  approved_categories: string[];
  denied_categories: string[];
  custom_overrides: Record<string, string>;
  last_run: string;
}

interface IntendedState {
  allowed: AllowedState & { updated: string };
  approvals: ApprovalsState;
  generated_permissions: string[];
}

function buildIntendedState(
  params: PermissionsInput,
  now: string,
): IntendedState {
  const bashCommands: string[] = [];
  const tools: string[] = [];
  for (const p of params.permissions) {
    const m = p.match(BASH_PATTERN);
    if (m) bashCommands.push(m[1]);
    else tools.push(p);
  }
  return {
    allowed: { bash_commands: bashCommands, tools, updated: now },
    approvals: {
      approved_categories: [
        ...new Set(["safe", ...params.approved_categories]),
      ],
      denied_categories: [...new Set(params.denied_categories)],
      custom_overrides: params.custom_overrides ?? {},
      last_run: now,
    },
    generated_permissions: params.permissions,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Diff
// ─────────────────────────────────────────────────────────────────────────

export interface Diff {
  added: string[];
  removed: string[];
  unchanged: string[];
}

function diffSets(current: Set<string>, proposed: Set<string>): Diff {
  const added: string[] = [];
  const removed: string[] = [];
  const unchanged: string[] = [];
  for (const p of proposed) (current.has(p) ? unchanged : added).push(p);
  for (const c of current) if (!proposed.has(c)) removed.push(c);
  added.sort();
  removed.sort();
  unchanged.sort();
  return { added, removed, unchanged };
}

function toAllowedDisplayForm(allowed: AllowedState): Set<string> {
  const out = new Set<string>();
  for (const b of allowed.bash_commands) out.add(`Bash(${b} *)`);
  for (const t of allowed.tools) out.add(t);
  return out;
}

function computeAllowedDiff(
  current: AllowedState,
  proposed: AllowedState,
): Diff {
  return diffSets(
    toAllowedDisplayForm(current),
    toAllowedDisplayForm(proposed),
  );
}

function computeCodexDiff(
  currentBaseCommands: string[],
  proposedBaseCommands: string[],
): Diff {
  return diffSets(
    new Set(currentBaseCommands.map((c) => `prefix_rule: ${c}`)),
    new Set(proposedBaseCommands.map((c) => `prefix_rule: ${c}`)),
  );
}

function readCurrentAllowed(): AllowedState {
  return (readJson(ALLOWED_PATH) ?? {
    bash_commands: [],
    tools: [],
  }) as AllowedState;
}

// ─────────────────────────────────────────────────────────────────────────
// Preview
// ─────────────────────────────────────────────────────────────────────────

export interface CodexPreview {
  installed: boolean;
  rules_path: string | null;
  proposed_rule_count: number;
  diff: Diff;
}

export interface PreviewResult {
  diff: Diff;
  proposed: {
    allowed: AllowedState & { updated: string };
    approvals: ApprovalsState;
  };
  paths: { allowed: string; approvals: string };
  codex: CodexPreview;
}

export function permissionsPreview(params: PermissionsInput): PreviewResult {
  const now = new Date().toISOString();
  const intended = buildIntendedState(params, now);
  const current = readCurrentAllowed();
  const codexLoc = locateCodex();
  const currentCodex =
    codexLoc.installed && codexLoc.rules_path
      ? parseCodexRulesBaseCommands(readText(codexLoc.rules_path))
      : [];
  const proposedBash = intended.allowed.bash_commands;
  return {
    diff: computeAllowedDiff(current, intended.allowed),
    proposed: { allowed: intended.allowed, approvals: intended.approvals },
    paths: { allowed: ALLOWED_PATH, approvals: APPROVALS_PATH },
    codex: {
      installed: codexLoc.installed,
      rules_path: codexLoc.rules_path,
      proposed_rule_count: codexLoc.installed ? proposedBash.length : 0,
      diff: codexLoc.installed
        ? computeCodexDiff(currentCodex, proposedBash)
        : { added: [], removed: [], unchanged: [] },
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Apply
// ─────────────────────────────────────────────────────────────────────────

export interface CodexApplyResult {
  installed: boolean;
  rules_path: string | null;
  rule_count: number;
  diff: Diff;
  error?: string;
}

export interface ApplyResult {
  success: true;
  diff: Diff;
  backup_path: string;
  allowed_path: string;
  approvals_path: string;
  codex: CodexApplyResult;
  details: string[];
}

function applyCodex(bashCommands: string[], now: string): CodexApplyResult {
  const loc = locateCodex();
  if (!loc.installed || !loc.rules_path || !loc.rules_dir) {
    return {
      installed: false,
      rules_path: null,
      rule_count: 0,
      diff: { added: [], removed: [], unchanged: [] },
    };
  }
  const currentBase = parseCodexRulesBaseCommands(readText(loc.rules_path));
  const diff = computeCodexDiff(currentBase, bashCommands);
  try {
    fs.mkdirSync(loc.rules_dir, { recursive: true });
    writeAtomic(loc.rules_path, buildCodexRules(bashCommands, now));
    return {
      installed: true,
      rules_path: loc.rules_path,
      rule_count: bashCommands.length,
      diff,
    };
  } catch (err) {
    return {
      installed: true,
      rules_path: loc.rules_path,
      rule_count: currentBase.length,
      diff,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export function permissionsApply(params: PermissionsInput): ApplyResult {
  const now = new Date().toISOString();
  const intended = buildIntendedState(params, now);
  const current = readCurrentAllowed();
  const diff = computeAllowedDiff(current, intended.allowed);
  const details: string[] = [];

  fs.mkdirSync(PERMISSIONS_DIR, { recursive: true });

  // 1. Backup first — timestamped filename makes this operation independent
  //    of any later step. If we crash after this, the user can restore.
  fs.mkdirSync(BACKUPS_DIR, { recursive: true });
  const dateStr = now.slice(0, 10);
  const timeStr = now.slice(11, 19).replace(/:/g, "");
  const backupPath = path.join(BACKUPS_DIR, `${dateStr}_${timeStr}.json`);
  const backup = {
    timestamp: now,
    repository: params.repository,
    skill_version: "6",
    categories: params.categories,
    generated_permissions: intended.generated_permissions,
    approvals_state: intended.approvals,
    previous_allowed: current,
    diff,
  };
  fs.writeFileSync(backupPath, `${JSON.stringify(backup, null, 2)}\n`);
  details.push(`Backup saved to ${backupPath}`);

  // 2. Commit allowed.json first — it drives enforcement. Each write is
  //    atomic per-file via tmp + rename. Multi-file atomicity is not
  //    possible without a journal; the window between the three renames
  //    is microseconds.
  writeJsonAtomic(ALLOWED_PATH, intended.allowed);
  details.push(
    `Allowed list written to ${ALLOWED_PATH} (${intended.allowed.bash_commands.length} Bash commands, ${intended.allowed.tools.length} tools)`,
  );

  writeJsonAtomic(APPROVALS_PATH, intended.approvals);
  details.push(`Approvals saved to ${APPROVALS_PATH}`);

  // 3. Codex rules — first-class target now. Errors are surfaced in the
  //    return value instead of swallowed; a Codex failure does NOT fail
  //    the apply call since allowed.json is the source of truth.
  const codex = applyCodex(intended.allowed.bash_commands, now);
  if (codex.installed && !codex.error) {
    details.push(
      `Codex rules written to ${codex.rules_path} (${codex.rule_count} rules)`,
    );
  } else if (codex.error) {
    details.push(
      `Codex rules write failed: ${codex.error} (allowed.json still committed)`,
    );
  }

  return {
    success: true as const,
    diff,
    backup_path: backupPath,
    allowed_path: ALLOWED_PATH,
    approvals_path: APPROVALS_PATH,
    codex,
    details,
  };
}
