/**
 * Setup/install utilities for external consumers.
 *
 * Extracted from cli.ts so fml-plugin (and other integrators) can run
 * panopticon setup steps without shelling out to the panopticon CLI.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { getOrCreateAuthToken } from "./auth.js";
import { config, ensureDataDir } from "./config.js";
import { refreshPricing } from "./db/pricing.js";
import { closeDb, getDb } from "./db/schema.js";
import { allTargets } from "./targets/index.js";

/**
 * Build the canonical list of panopticon env vars (`[name, value]` tuples).
 *
 * Used by both the shell-rc writer and the dedicated env-file writer below.
 * Includes the auth token in OTEL_EXPORTER_OTLP_HEADERS so OTLP-emitting
 * agents can authenticate against the gated /v1/* server.
 *
 * `proxy` controls whether target adapters return their proxy-related vars
 * (e.g. ANTHROPIC_BASE_URL → /proxy/anthropic).
 */
export function buildPanopticonEnvVars(
  proxy: boolean,
): Array<[string, string]> {
  const token = getOrCreateAuthToken();
  const vars: Array<[string, string]> = [
    ["OTEL_EXPORTER_OTLP_ENDPOINT", `http://localhost:${config.port}`],
    ["OTEL_EXPORTER_OTLP_PROTOCOL", "http/protobuf"],
    // Per the OTel spec the value is URL-encoded — encode the space
    // between "Bearer" and the token. The hex token needs no encoding.
    ["OTEL_EXPORTER_OTLP_HEADERS", `Authorization=Bearer%20${token}`],
    ["OTEL_METRICS_EXPORTER", "otlp"],
    ["OTEL_LOGS_EXPORTER", "otlp"],
    ["OTEL_LOG_TOOL_DETAILS", "1"],
    ["OTEL_LOG_USER_PROMPTS", "1"],
    ["OTEL_METRIC_EXPORT_INTERVAL", "10000"],
  ];
  for (const t of allTargets()) {
    for (const [name, value] of t.shellEnv.envVars(config.port, proxy)) {
      vars.push([name, value]);
    }
  }
  return vars;
}

/**
 * Write a guaranteed-sourcable env file at `<dataDir>/env.sh`.
 *
 * The standard Debian/Ubuntu `~/.bashrc` aborts early for non-interactive
 * shells, which means scripts that `source ~/.bashrc` get nothing from the
 * panopticon block — including OTEL_EXPORTER_OTLP_HEADERS, breaking auth
 * on /v1/*. This file has no such guard: any caller that sources it gets
 * the full panopticon environment.
 *
 * The file contains the auth token, so it's written 0600.
 *
 * Returns the path to the written file.
 */
export function writePanopticonEnvFile(proxy: boolean): string {
  // Resolve dataDir at call time so PANOPTICON_DATA_DIR overrides (used
  // heavily in tests) take effect even when this module was imported
  // before the env var was set.
  const dataDir = process.env.PANOPTICON_DATA_DIR ?? config.dataDir;
  fs.mkdirSync(dataDir, { recursive: true });
  const fp = path.join(dataDir, "env.sh");
  const lines = [
    "# Auto-generated by panopticon — source this for the panopticon shell env.",
    "# Equivalent to the `# >>> panopticon` block in your shell rc, but safe",
    "# to source from non-interactive scripts (no early-return guard).",
    ...buildPanopticonEnvVars(proxy).map(
      ([name, value]) => `export ${name}=${value}`,
    ),
    "",
  ];
  fs.writeFileSync(fp, lines.join("\n"), { mode: 0o600 });
  return fp;
}

/**
 * Initialize the panopticon database — creates the data directory,
 * schema, indexes, and runs migrations.
 */
export function initDb(): void {
  ensureDataDir();
  getDb();
  closeDb();
}

/**
 * Fetch model pricing from LiteLLM and cache locally.
 * Returns the number of models cached, or null if the fetch failed.
 */
export async function fetchPricing(): Promise<number | null> {
  const result = await refreshPricing();
  return result ? Object.keys(result.models).length : null;
}

export interface ShellEnvOptions {
  /** Overwrite user-customized env vars (default false) */
  force?: boolean;
  /** Target CLI target id or "all" (default "claude") */
  target?: string;
  /** Also configure API proxy (default false) */
  proxy?: boolean;
}

/**
 * Configure shell environment variables (.zshrc / .bashrc) so that
 * coding tools send telemetry to panopticon.
 *
 * Returns the path to the shell rc file that was updated.
 */
export function configureShellEnv(opts: ShellEnvOptions = {}): string {
  const force = opts.force ?? false;
  const target = opts.target ?? "claude";
  const proxy = opts.proxy ?? false;

  const shellRc = path.join(
    os.homedir(),
    process.env.SHELL?.includes("zsh") ? ".zshrc" : ".bashrc",
  );
  const rcContent = fs.existsSync(shellRc)
    ? fs.readFileSync(shellRc, "utf-8")
    : "";

  // Collect all known target env var names for detection/cleanup
  const allTargetVarNames = new Set<string>();
  for (const v of allTargets()) {
    for (const [varName] of v.shellEnv.envVars(config.port, true)) {
      allTargetVarNames.add(varName);
    }
  }

  const PANOPTICON_VARS = [
    "OTEL_EXPORTER_OTLP_ENDPOINT",
    "OTEL_EXPORTER_OTLP_PROTOCOL",
    "OTEL_EXPORTER_OTLP_HEADERS",
    "OTEL_METRICS_EXPORTER",
    "OTEL_LOGS_EXPORTER",
    "OTEL_LOG_TOOL_DETAILS",
    "OTEL_LOG_USER_PROMPTS",
    "OTEL_METRIC_EXPORT_INTERVAL",
    ...allTargetVarNames,
  ];
  const PANOPTICON_COMMENTS = ["# >>> panopticon", "# <<< panopticon"];

  const isPanopticonLine = (line: string): boolean => {
    const trimmed = line.trim();
    if (PANOPTICON_COMMENTS.some((c) => trimmed.startsWith(c))) return true;
    for (const v of PANOPTICON_VARS) {
      if (trimmed === `export ${v}` || trimmed.startsWith(`export ${v}=`))
        return true;
    }
    return false;
  };

  // Generate the auth token once so the bashrc and the env.sh file both
  // contain the same OTEL_EXPORTER_OTLP_HEADERS value.
  const authToken = getOrCreateAuthToken();

  // Build the wanted env vars: shared OTEL vars + target-specific vars
  const wantedLines: [string, string][] = [
    ["# >>> panopticon >>>", "# >>> panopticon >>>"],
    [
      "OTEL_EXPORTER_OTLP_ENDPOINT",
      `export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:${config.port}`,
    ],
    [
      "OTEL_EXPORTER_OTLP_PROTOCOL",
      "export OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf",
    ],
    [
      "OTEL_EXPORTER_OTLP_HEADERS",
      `export OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer%20${authToken}`,
    ],
    ["OTEL_METRICS_EXPORTER", "export OTEL_METRICS_EXPORTER=otlp"],
    ["OTEL_LOGS_EXPORTER", "export OTEL_LOGS_EXPORTER=otlp"],
    ["OTEL_LOG_TOOL_DETAILS", "export OTEL_LOG_TOOL_DETAILS=1"],
    ["OTEL_LOG_USER_PROMPTS", "export OTEL_LOG_USER_PROMPTS=1"],
    ["OTEL_METRIC_EXPORT_INTERVAL", "export OTEL_METRIC_EXPORT_INTERVAL=10000"],
  ];

  // Add target-specific env vars for selected targets
  const selectedTargetList =
    target === "all"
      ? allTargets()
      : allTargets().filter((v) => v.id === target);

  for (const t of selectedTargetList) {
    for (const [varName, value] of t.shellEnv.envVars(config.port, proxy)) {
      wantedLines.push([varName, `export ${varName}=${value}`]);
    }
  }

  wantedLines.push(["# <<< panopticon <<<", "# <<< panopticon <<<"]);

  if (!rcContent.includes(".local/bin")) {
    wantedLines.splice(1, 0, [
      "PATH_LOCAL_BIN",
      'export PATH="$HOME/.local/bin:$PATH"',
    ]);
  }

  const lines = rcContent.split("\n");
  const preservedLines: string[] = [];
  const existingByKey = new Map<string, string>();
  let insertAt = -1;

  for (const line of lines) {
    if (!isPanopticonLine(line)) {
      preservedLines.push(line);
      continue;
    }

    if (insertAt < 0) {
      insertAt = preservedLines.length;
    }

    const match = wantedLines.find(([key]) => {
      if (key.startsWith("#")) return line.trim().startsWith(key);
      return (
        line.trim() === `export ${key}` ||
        line.trim().startsWith(`export ${key}=`)
      );
    });
    if (match) {
      existingByKey.set(match[0], line.trim());
    }
  }

  const resolvedBlock = wantedLines.map(([key, value]) => {
    if (force || key.startsWith("#")) return value;
    return existingByKey.get(key) ?? value;
  });

  const insertionIndex = insertAt >= 0 ? insertAt : preservedLines.length;
  const blockLines = ["", ...resolvedBlock, ""];
  preservedLines.splice(insertionIndex, 0, ...blockLines);

  fs.writeFileSync(shellRc, preservedLines.join("\n"));

  // Also write the dedicated env file so non-interactive callers (CI,
  // docker entrypoints, e2e scripts) can source the panopticon env without
  // depending on the standard `~/.bashrc` non-interactive guard.
  writePanopticonEnvFile(proxy);

  return shellRc;
}

// Re-export config for convenience (port, paths, etc.)
export { config } from "./config.js";
